### ISSUE TITLE
Remove the need to add api-key everywhere

### ISSUE THREAD

**Issue by foxish** [signadot/examples#3]
https://github.com/signadot/examples/blob/main/java-sdk-demo/src/test/java/RouteServiceTest.java#L85

cc @jmsktm

**Comment by jmsktm** [comment]
@foxish : I have made these changes to java and sdk demos to not set the header directly while running the tests.

* **Java example**: I am building a spec that is passed when running a test.
* **Node example: It's almost the same thing, but just a little cleaner way of passing an already created options object with headers set to it. I resorted to this after the attempt to pre-set the header to axios object didn't work because of caching issues.

Lmk if you think this needs further improvement.

**Comment by foxish** [comment]
Looks good! Thanks @jmsktm
